name: CICD Pipeline - Build & Deploy to AWS EC2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  server-check:
    name: Server Check
    runs-on: ubuntu-latest
    steps:
      - name: Check system info
        run: |
          echo "Node Version:"
          node -v
          echo "Git Version:"
          git --version
          echo "Current Directory:"
          whoami && pwd && ls -a
          echo "GitHub Workspace:"
          echo $GITHUB_WORKSPACE

  build:
    name: Build App
    runs-on: ubuntu-latest
    needs: [server-check]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Build Project
        run: yarn build

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            .yarn/cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

  deploy:
    name: Deploy to AWS EC2
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy via SSH to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "."
          target: "/home/${{ secrets.EC2_USER }}/ts-node-server"

      - name: SSH Run Remote Script
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ts-node-server
            yarn install --production
            pm2 restart all || pm2 start dist/server.js --name ts-node-server
