name: Formatter and Linting Check

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with: 
          node-version: 20
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Run ESLint
        run: |
          echo "Stating linting with ESLint..."
          yarn lint
      - name: Run Prettier
        run: |
          echo "Starting formatting with Prettier..."
          yarn lint